min_points: 240
max_points: 270

telegrams:
  - jwt_token: "Bearer eyJ...."
    proxy: "http://user:password@host:port"
  - jwt_token: "Bearer eyJ...."
    proxy: "https://user:password@host:port"

cpu_count: 12